# Generated by Django 2.1.5 on 2019-02-19 16:22

from django.db import migrations, models
import django.db.models.deletion
import myapp.models
import myapp.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_id', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_skpd', models.CharField(max_length=17)),
                ('nama_pemilik', models.CharField(max_length=255)),
                ('alamat_pemilik', models.CharField(max_length=255)),
                ('area_koordinasi_pemilik', models.CharField(max_length=255)),
                ('isi_teks', models.CharField(max_length=255)),
                ('tempat_pemasangan', models.CharField(max_length=255)),
                ('lokasi_pemasangan', models.CharField(max_length=255)),
                ('kota_lokasi_pemasangan', models.CharField(max_length=255)),
                ('kecamatan_lokasi_pemasangan', models.CharField(max_length=255)),
                ('kelurahan_lokasi_pemasangan', models.CharField(max_length=255)),
                ('masa_berlaku_awal', models.DateField()),
                ('masa_berlaku_akhir', models.DateField()),
                ('nilai_sewa', models.IntegerField()),
                ('pdf_file', models.FileField(blank=True, default=None, storage=myapp.storages.OverwriteStorage(), upload_to=myapp.models.skpd_pdf_file_path)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ukuran',
            fields=[
                ('skpd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.SKPD')),
                ('panjang_1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lebar_1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('panjang_2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lebar_2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('panjang_3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lebar_3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('panjang_4', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lebar_4', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='skpd',
            name='atm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ATM'),
        ),
    ]
