# Generated by Django 2.1.4 on 2019-01-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ukuran',
            name='total',
        ),
    ]
