# Generated by Django 2.1.4 on 2019-01-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_ukuran_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skpd',
            name='atm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ATM'),
        ),
    ]
