from django import forms

from .models import ATM, SKPD, Ukuran
from django.conf import settings

class ATMForm(forms.Form):
    atm_id                      = forms.CharField(label='ID ATM', max_length=10)
    no_skpd                     = forms.CharField(label='Nomor SKPD', max_length=19)
    nama_pemilik                = forms.CharField(label='Nama Pemilik Reklame', max_length=255)
    alamat_pemilik              = forms.CharField(label='Alamat', max_length=255)
    area_koordinasi_pemilik     = forms.CharField(label='Area Koordinasi', max_length=255)
    isi_teks                    = forms.CharField(label='Isi Teks Reklame', max_length=255)
    tempat_pemasangan           = forms.CharField(label='Tempat Pemasangan', max_length=255)
    lokasi_pemasangan           = forms.CharField(label='Lokasi Pemasangan', max_length=255)
    kota_lokasi_pemasangan      = forms.CharField(label='Kota', max_length=255)
    kecamatan_lokasi_pemasangan = forms.CharField(label='Kecamatan', max_length=255)
    kelurahan_lokasi_pemasangan = forms.CharField(label='Kelurahan', max_length=255)
    panjang_1                   = forms.DecimalField(label='Panjang', max_digits=3, decimal_places=2)
    lebar_1                     = forms.DecimalField(label='Lebar', max_digits=3, decimal_places=2)
    panjang_2                   = forms.DecimalField(label='Panjang', max_digits=3, decimal_places=2)
    lebar_2                     = forms.DecimalField(label='Lebar', max_digits=3, decimal_places=2)
    panjang_3                   = forms.DecimalField(label='Panjang', max_digits=3, decimal_places=2)
    lebar_3                     = forms.DecimalField(label='Lebar', max_digits=3, decimal_places=2)
    panjang_4                   = forms.DecimalField(label='Panjang', max_digits=3, decimal_places=2)
    lebar_4                     = forms.DecimalField(label='Lebar', max_digits=3, decimal_places=2)
    masa_berlaku_awal           = forms.DateField(label='Masa Pajak Reklame (Awal)', input_formats=settings.DATE_INPUT_FORMATS, widget=forms.widgets.DateInput(format="%d-%m-%Y"))
    masa_berlaku_akhir          = forms.DateField(label='Masa Pajak Reklame (Akhir)', input_formats=settings.DATE_INPUT_FORMATS, widget=forms.widgets.DateInput(format="%d-%m-%Y"))
    nilai_sewa                  = forms.IntegerField(label='Nilai Sewa Reklame')
    pdf_file                    = forms.FileField(label='PDF File (.pdf)', required=False)
    image_file                  = forms.FileField(label='Foto Reklame (.jpg)', required=False)
    comment                     = forms.CharField(label='Comment', widget=forms.Textarea, required=False)

class SKPDForm(forms.Form):
    no_skpd                     = forms.CharField(label='Nomor SKPD', max_length=19)
    nama_pemilik                = forms.CharField(label='Nama Pemilik Reklame', max_length=255)
    alamat_pemilik              = forms.CharField(label='Alamat', max_length=255)
    area_koordinasi_pemilik     = forms.CharField(label='Area Koordinasi', max_length=255)
    isi_teks                    = forms.CharField(label='Isi Teks Reklame', max_length=255)
    tempat_pemasangan           = forms.CharField(label='Tempat Pemasangan', max_length=255)
    lokasi_pemasangan           = forms.CharField(label='Lokasi Pemasangan', max_length=255)
    kota_lokasi_pemasangan      = forms.CharField(label='Kota', max_length=255)
    kecamatan_lokasi_pemasangan = forms.CharField(label='Kecamatan', max_length=255)
    kelurahan_lokasi_pemasangan = forms.CharField(label='Kelurahan', max_length=255)
    panjang_1                   = forms.DecimalField(label='Panjang', max_digits=3, decimal_places=2)
    lebar_1                     = forms.DecimalField(label='Lebar', max_digits=3, decimal_places=2)
    panjang_2                   = forms.DecimalField(label='Panjang', max_digits=3, decimal_places=2)
    lebar_2                     = forms.DecimalField(label='Lebar', max_digits=3, decimal_places=2)
    panjang_3                   = forms.DecimalField(label='Panjang', max_digits=3, decimal_places=2)
    lebar_3                     = forms.DecimalField(label='Lebar', max_digits=3, decimal_places=2)
    panjang_4                   = forms.DecimalField(label='Panjang', max_digits=3, decimal_places=2)
    lebar_4                     = forms.DecimalField(label='Lebar', max_digits=3, decimal_places=2)
    masa_berlaku_awal           = forms.DateField(label='Masa Pajak Reklame (Awal)', input_formats=settings.DATE_INPUT_FORMATS, widget=forms.widgets.DateInput(format="%d-%m-%Y"))
    masa_berlaku_akhir          = forms.DateField(label='Masa Pajak Reklame (Akhir)', input_formats=settings.DATE_INPUT_FORMATS, widget=forms.widgets.DateInput(format="%d-%m-%Y"))
    nilai_sewa                  = forms.IntegerField(label='Nilai Sewa Reklame')
    pdf_file                    = forms.FileField(label='PDF File (.pdf)', required=False)
    image_file                  = forms.FileField(label='Foto Reklame (.jpg)', required=False)
    comment                     = forms.CharField(label='Comment', widget=forms.Textarea, required=False)
